http:
  host: "0.0.0.0"
  port: "8081"
  
mule:
  version: "4.4.0"
anypoint:
  username: "DevMax"
  password: "MuleMax2021"
  
cloudhub:
  enviroment: "Sandbox"
  app: "blueOcean_sh"
  worker: "Micro"
  workers: "1"
  region: "us-west-1"